export const ACTIONS = {
    ADD_ITEM: "ADD_ITEM",
    REM_ITEM: "REM_ITEM",
    MOVE_ITEM: "MOVE_ITEM",
    ADD_VITAL: "ADD_VITAL",
    REM_VITAL: "REM_VITAL",
    MOVE_VITAL: "MOVE_VITAL",
    ADD_WEAPON: "ADD_WEAPON",
    REM_WEAPON: "REM_WEAPON",
    MOVE_WEAPON: "MOVE_WEAPON",
    ADD_WEAPONMOD: "ADD_WEAPONMOD",
    REM_WEAPONMOD: "REM_WEAPONMOD",
    MOVE_WEAPONMOD: "MOVE_WEAPONMOD",
    ADD_VEHICLE: "ADD_VEHICLE",
    REM_VEHICLE: "REM_VEHICLE",
    MOVE_VEHICLE: "MOVE_VEHICLE",
    ADD_VEHICLEITEM: "ADD_VEHICLEITEM",
    REM_VEHICLEITEM: "REM_VEHICLEITEM",
    MOVE_VEHICLEITEM: "MOVE_VEHICLEITEM",
}

export function addItem(item){
    return (dispatch) => {
        dispatch({type: ACTIONS.ADD_ITEM, data: {item}})
    }
}